### ISSUE TITLE
Img file rejected by router

### ISSUE THREAD

**Issue by Antaraki2004** [nikolas-n/Speedport-Plus-Cosmote-Router-hacks#11]
After downloading the `.img` file provided, I was met with the following message:

> Result of firmware file check
> The selcted file is not a valid firmware file. Please select a file with a valid update for your Speedport model.

The firmware version currently installed is `09022001.00.035_OTE5`, which seems to be newer than the one mentioned in the repo. Is there any chance that COSMOTE implemented checks on the latest update to stop firmware downgrading?
![image](https://user-images.githubusercontent.com/26285040/174041122-55407c46-1bc9-4653-ac95-9ca8dd340c74.png)

**Comment by nikolas-n** [comment]
Very likely, maybe someone can confirm.

Just to be sure, have you checked that the file you're uploading is around 18MBs?

**Comment by Antaraki2004** [comment]
According to the file properties, the exact size is `18.8 MB (19,792,336 bytes)`. I should mention here that I am currently on Windows 10 and Microsoft is known for incorrectly measuring storage in powers of 2 instead of 10, so the number could be slightly inaccurate, depending on the number reported on a different OS.

I made sure to also redownload the file to make sure the first download wasn't corrupted. The new download was of the exact same size and wields the same results when selected at the Speedport Plus configuration portal.

**Comment by nikolas-n** [comment]
Ok, then we can leave this open, in case someone else wants to try on their router. To me it seems like that Cosmote noticed that and cut it off in the newer firmwares.

**Comment by nikolas-n** [comment]
@Antaraki2004 , since you opened Issue #12 I guess you managed to retrieve the VoIP credentials.
Closing this down.

**Comment by neos21-zz** [comment]
Hello! First, I am not sure that I understand the instructions 

> 1. Make sure you have git lfs installed. This step is needed so that the repo is cloned along with the img file
> 2. Clone this repo

Ignoring the above and attempting to flash the 09022001_00_021.img (my Windows machine shows the same file size as Antaraki2004), I get the same rejection as Antarakli2004. My current firmware is 09022001.00.031_OTE2, even older compared to Antaraki2004.

Antaraki2004, did you manage to flash the img file?

**Comment by Antaraki2004** [comment]
No, I didn't manage to flash the img file.

**Comment by Antaraki2004** [comment]
> @Antaraki2004 , since you opened Issue #12 I guess you managed to retrieve the VoIP credentials. Closing this down.

@nikolas-n The VoIP credentials were obtained through other means; the issue of being unable to flash old firmware to obtain them through the configuration portal persists. I recommend reopening this issue as it's still relevant.
