### ISSUE TITLE
Hello! First, I am not sure that I understand the instructions

### ISSUE THREAD

**Issue by neos21-zz** [nikolas-n/Speedport-Plus-Cosmote-Router-hacks#13]
Hello! First, I am not sure that I understand the instructions 

> 1. Make sure you have git lfs installed. This step is needed so that the repo is cloned along with the img file
> 2. Clone this repo

Ignoring the above and attempting to flash the 09022001_00_021.img (my Windows machine shows the same file size as Antaraki2004), I get the same rejection as Antarakli2004. My current firmware is 09022001.00.031_OTE2, even older compared to Antaraki2004.

Antaraki2004, did you manage to flash the img file?

_Originally posted by @neos21-zz in https://github.com/nikolas-n/Speedport-Plus-Cosmote-Router-hacks/issues/11#issuecomment-1227691562_

**Comment by adrianmihalko** [comment]
Hi, I have this router from Slovak Telekom. Unfortunately advanced settings are hidden and I can't make any static routes. If anyone found a workaround, please let me know.
