### ISSUE TITLE
How can i reboot the speedport entry 2i

### ISSUE THREAD

**Issue by GiannisDorokidis** [nikolas-n/Speedport-Plus-Cosmote-Router-hacks#16]
im trying to make a curl command or a bash script that will reboot the speedport entry 2i
i tried using the reboot.sh (that is meant for the speedport plus) but i couldnt get it to work i run ./reboot.sh user password
it didnt work. I have all dependencies like curl and jq

**Comment by nikolas-n** [comment]
sorry, this repo only covers the Speedport Plus. I'm closing this
