### ISSUE TITLE
Getting answered and dialed calls too

### ISSUE THREAD

**Issue by pitsi** [nikolas-n/Speedport-Plus-Cosmote-Router-hacks#17]
I am a happy user of your missed_calls.sh script since I switched to speedport plus ~9 months ago because I no longer have to leave the pc in order to check who called.
Because anyone can delete any call from the phone device itself, I would like to have a fallback option for received and dialed calls too.

I am 100% certain that these calls are also included in `http://192.168.1.1/data/PhoneCalls.json`, but I do not know how to parse them. Can you show me please? Thank you in advance.

**Comment by nikolas-n** [comment]
hi @pitsi 
Just added another two scripts, it was faster than having everything into one.
thanks!

**Comment by pitsi** [comment]
Thank you so much! As it seems, they were just 2 different variables like the one for the missed calls.
Well done for finding them.
