### ISSUE TITLE
error with login command

### ISSUE THREAD

**Issue by delazaren** [nikolas-n/Speedport-Plus-Cosmote-Router-hacks#2]
Hi Nikola,

Not sure that this is where I can ask a question...

when I tried to issue the following command 

`curl -c - -H 'Accept-Language: en' "http://192.168.1.1/data/Login.json" -d "showpw=0" -d "username=*****" -d "password=*****"`

I got an error saying that host could not be found. 

(not sure but I think the second "orphaned" dash is erroneous so I replaced it with a file name)

The router had the latest firmware (OTE5) but when I tried to downgrade with the file I found on the "pull request" link so that I could try again the login command, I unfortunately fried it.

**Comment by nikolas-n** [comment]
Is the IP pingable? Are you sure that this is the IP of your router? 192.168.1.1 is the default IP, but you may have changed it to something else and forgot it?

Also, the problem might be related to the version of the cURL you're using?

**Comment by delazaren** [comment]
Hi Nikola,

I'm pretty sure that it was pingable, and I did use the latest version of curl - but no worries, since I "fried" it, I had it replaced with the Speedport Smart - but I'm not using that either as if I connect it to the line it will get configured by COSMOTE which will change the password for the VOIP and I cannot afford to have that changed again. Currently i'm using a Vigor router and have set it up to have two VOIP numbers (one is the one from COSMOTE).
