### ISSUE TITLE
Can't connect to VoIP Server

### ISSUE THREAD

**Issue by bkbilly-intrack** [nikolas-n/Speedport-Plus-Cosmote-Router-hacks#4]
I love the work you've done for the router and I liked the idea of having my landline anywhere, so I downgraded my router to 09022001_00_021 so that I can use the IPPhoneHandler.json request to get the password.

Everything worked great and I got the password, but when I try to register with my VoIP client, it is not able even though I disable the VoIP on my router.
I've tried different clients, like CsipSimple, Linphone, Asterisk, but I still can't connect.

I think that I have configured everything correctly, so I thought I could create an issue here to ask you for any tips.

**Comment by nikolas-n** [comment]
Thanks for your kind words!

I think I still have my credentials, so I'll try that. I don't find it very improbable that OTE might be blocking logins from other clients... Can you elaborate on what error you're getting? Do you have any logs?

**Comment by nikolas-n** [comment]
just tried and managed to make a call and receive one.
i'm using Twinkle 1.10 on Debian Bullseye. I don't have any specific configuration/setup, so I believe it should work on any other client.

**Comment by bkbilly-intrack** [comment]
Thanks for taking a look.
On Asterisk I get authentication failed, on CSipSimple I get a timeout and Linphone is constantly trying to connect.

I think that my problem is related with Cosmote because I have FTTH, so I will close this issue because there is nothing that you can do to fix it.
