### ISSUE TITLE
bricked?

### ISSUE THREAD

**Issue by gecon27** [nikolas-n/Speedport-Plus-Cosmote-Router-hacks#6]
Hello,
I am writing in English so that also non-Greeks can read.
My goal was to retrieve the VoIP credentials but I think I bricked the router.
The version of the router when I received it some days ago was 09022001.00.031_OTE2 (09022001.00.031_OTE2.img).
First, I tried to upload firmware 09022001_00_021.img directly, but this did not work as the router gave a popup that the firmware was not correct.
Then, after reading another issue in this project, I tried to upload as an intermediate step firmware 09022001.00.030_OTE5.img. This worked successfully, so afterwards I tried again to upload 09022001_00_021.img. Although the firmware was accepted this time, ever since I am not able to connect to the router (either via cable or wifi).
After doing some tests, I found out that network access (cable and wifi) is blocked completely a few seconds after the router is up. In these few seconds I am able to connect for e.g. via cable and I checked that the firmware is indeed now 09022001_00_021. Any attempt to upload another firmware is not possible as network is blocked a few seconds later.
Trying factory reset did not help either. Behavior remains the same.
Any ideas are welcome. If you are in Athens, I am willing to meet and bring it to you if you think you can do something, otherwise most probably I will buy a new one (I hope it will be possible to plug it on the same line and that no MAC/serial number checks are done by COSMOTE). Send me a personal message and I can provide you with my mobile phone to talk if ok with you.
Moreover, if I buy a new one, most probably it will be on the latest firmware 09022001.00.031_OTE2 as it was mine. Is there a way to retrieve the VoIP credentials on this firmware?
Thanks,
Giannis

**Comment by tatokis** [comment]
I don't know if it will help, but try unplugging the phone line so that it doesn't try to get online.

While I have never had to downgrade, whenever mine syncs with the DSLAM, I can't access it any more even though it's still forwarding packets, and the only way to be able to manage it is to leave the phone line unplugged before it gets to that point.

**Comment by gecon27** [comment]
@tatokis: Thanks. I have already removed all cables. Forgot to mention that this is a FTTH connection (Ethernet coming from GPON device is connected on LAN1 which acts as WAN port), so no DSL.

**Comment by Notupus** [comment]
Hi, I have done some investigation, if you are able send me an email over at notpp46@googlemail.com . I have some experience in debugging those routers, I have tested HWrev1 and HWrev2.

**Comment by nikolas-n** [comment]
Closing this down due to inactivity, you can always re-open if need be. thanks
